### ISSUE TITLE
`send_xxx` doesn't escape data

### ISSUE THREAD

**Issue by iirekm** [EinGuterWaran/pushbullet-python#1]
`data = '{"body":"' + body + '","title":"' + title + '","type":"link", "url":"' + url_to_send + '"}'`  is a serious security issue (from the "injection" category), plus many strings (.e.g. those that contain `"`) simply don't work.
Proper approach: `json.dumps(dict(body=..., title=..., ...))`

**Comment by EinGuterWaran** [comment]
@iirekm Thank you! Fixed.
